version: '3.8'
services:
  backend:
    command: python main.py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    environment:
    container_name: 'template'

